/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this
 * license Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.UserController;
import Model.UserModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Rayhan Faridh
 */
public class ChangePasswordPanel extends javax.swing.JPanel {

    private final UserModel member;

    /**
     * Creates new form EditProfilePanel
     */
    public ChangePasswordPanel(UserModel user) {
        initComponents();
        this.member = user;
        setFormValue(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataMembersPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nimLabel = new javax.swing.JLabel();
        newPassLabel = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        nimField = new javax.swing.JTextField();
        oldPassLabel = new javax.swing.JLabel();
        oldPassField = new javax.swing.JPasswordField();
        newPassField = new javax.swing.JPasswordField();
        confirmPassLabel = new javax.swing.JLabel();
        confirmPassField = new javax.swing.JPasswordField();

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 252, 230));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataMembersPanel.setBackground(new java.awt.Color(255, 252, 230));

        titlePanel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titlePanel.setText("CHANGE PASSWORD");

        nimLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nimLabel.setText("NIM:");

        newPassLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newPassLabel.setText("Password Baru:");

        btnSimpan.setBackground(new java.awt.Color(0, 123, 255));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(108, 117, 125));
        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.setBorder(null);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        nimField.setEditable(false);
        nimField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        oldPassLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        oldPassLabel.setText("Password Lama:");

        confirmPassLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmPassLabel.setText("Konfirmasi Password:");

        javax.swing.GroupLayout dataMembersPanelLayout =
                new javax.swing.GroupLayout(dataMembersPanel);
        dataMembersPanel.setLayout(dataMembersPanelLayout);
        dataMembersPanelLayout.setHorizontalGroup(dataMembersPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataMembersPanelLayout.createSequentialGroup().addContainerGap()
                        .addGroup(dataMembersPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dataMembersPanelLayout.createSequentialGroup()
                                        .addGroup(dataMembersPanelLayout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jSeparator1).addComponent(titlePanel,
                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 736,
                                                        Short.MAX_VALUE))
                                        .addGap(12, 12, 12))
                                .addGroup(dataMembersPanelLayout.createSequentialGroup()
                                        .addGroup(dataMembersPanelLayout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(newPassLabel,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(oldPassLabel,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nimLabel,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(dataMembersPanelLayout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        false)
                                                .addComponent(oldPassField,
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nimField,
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(newPassField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 250,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(dataMembersPanelLayout
                                                        .createSequentialGroup()
                                                        .addComponent(btnReset,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                94,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnSimpan,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                94,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGroup(dataMembersPanelLayout.createSequentialGroup()
                                        .addComponent(confirmPassLabel,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(confirmPassField,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 250,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))));
        dataMembersPanelLayout.setVerticalGroup(dataMembersPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataMembersPanelLayout
                        .createSequentialGroup().addContainerGap()
                        .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataMembersPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                        false)
                                .addComponent(nimLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30,
                                        Short.MAX_VALUE)
                                .addComponent(nimField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataMembersPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                        false)
                                .addComponent(oldPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        30, Short.MAX_VALUE)
                                .addComponent(oldPassField))
                        .addGap(7, 7, 7)
                        .addGroup(dataMembersPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(newPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dataMembersPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(confirmPassLabel,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(confirmPassField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dataMembersPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(330, 330, 330)));

        mainPanel.add(dataMembersPanel, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private boolean btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {
        String nim = nimField.getText();
        String oldPass = new String(oldPassField.getPassword());
        String newPass = new String(newPassField.getPassword());
        String confirmPass = new String(confirmPassField.getPassword());

        if (oldPass.isEmpty() || newPass.isEmpty() || confirmPass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua kolom harus diisi!", "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!newPass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(null, "Password baru dan konfirmasi password tidak sama!",
                    "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        UserController userController = new UserController();
        userController.changePassword(nim, oldPass, newPass);
        return true;
    }// GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetActionPerformed
        setFormValue(member);
    }// GEN-LAST:event_btnResetActionPerformed

    private void setFormValue(UserModel user) {
        nimField.setText(user.getNim());
        oldPassField.setText("");
        newPassField.setText("");
        confirmPassField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel confirmPassLabel;
    private javax.swing.JPanel dataMembersPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField newPassField;
    private javax.swing.JLabel newPassLabel;
    private javax.swing.JTextField nimField;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JPasswordField oldPassField;
    private javax.swing.JLabel oldPassLabel;
    private javax.swing.JLabel titlePanel;
    // End of variables declaration//GEN-END:variables
}
