/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import jiconfont.swing.IconFontSwing;
import jiconfont.icons.font_awesome.FontAwesome;

import Model.UserModel;

/**
 *
 * @author Muhammad Rayhan Faridh
 */
public class HomePanel extends javax.swing.JPanel {

    private final UserModel model;

    /**
     * Creates new form HomePanel
     */
    public HomePanel(UserModel userModel) {
        initComponents();
        IconFontSwing.register(FontAwesome.getIconFont());

        this.model = userModel;

        Icon bphIcon = IconFontSwing.buildIcon(FontAwesome.USER_SECRET, 58);
        ImageIcon devIcon = new ImageIcon(getClass().getResource("../images/user-gear-solid.png"));
        ImageIcon eduIcon = new ImageIcon(getClass().getResource("../images/person-chalkboard-solid.png"));
        ImageIcon hpdIcon = new ImageIcon(getClass().getResource("../images/user-with-camera.png"));
        Icon umumIcon = IconFontSwing.buildIcon(FontAwesome.USER, 58);

        cardIcon1.setIcon(bphIcon);
        cardIcon2.setIcon(devIcon);
        cardIcon3.setIcon(eduIcon);
        cardIcon4.setIcon(hpdIcon);
        cardIcon5.setIcon(umumIcon);

        cardCounter1.setText(String.valueOf(model.getMemberCount("BPH")) + " orang");
        cardCounter2.setText(String.valueOf(model.getMemberCount("Pengembangan")) + " orang");
        cardCounter3.setText(String.valueOf(model.getMemberCount("Pelatihan")) + " orang");
        cardCounter4.setText(String.valueOf(model.getMemberCount("HPD")) + " orang");
        cardCounter5.setText(String.valueOf(model.getMemberCount("Umum")) + " orang");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bphPanel = new javax.swing.JPanel();
        cardIcon1 = new javax.swing.JLabel();
        cardCounter1 = new javax.swing.JLabel();
        cardTitle1 = new javax.swing.JLabel();
        pengembanganPanel = new javax.swing.JPanel();
        cardIcon2 = new javax.swing.JLabel();
        cardCounter2 = new javax.swing.JLabel();
        cardTitle2 = new javax.swing.JLabel();
        pelatihanPanel = new javax.swing.JPanel();
        cardIcon3 = new javax.swing.JLabel();
        cardCounter3 = new javax.swing.JLabel();
        cardTitle3 = new javax.swing.JLabel();
        hpdPanel = new javax.swing.JPanel();
        cardIcon4 = new javax.swing.JLabel();
        cardCounter4 = new javax.swing.JLabel();
        cardTitle4 = new javax.swing.JLabel();
        umumPanel = new javax.swing.JPanel();
        cardIcon5 = new javax.swing.JLabel();
        cardCounter5 = new javax.swing.JLabel();
        cardTitle5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 252, 230));

        cardIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cardCounter1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cardCounter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardCounter1.setText("counter");

        cardTitle1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cardTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardTitle1.setText("BPH");

        javax.swing.GroupLayout bphPanelLayout = new javax.swing.GroupLayout(bphPanel);
        bphPanel.setLayout(bphPanelLayout);
        bphPanelLayout.setHorizontalGroup(
            bphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bphPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(bphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(cardCounter1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(cardIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        bphPanelLayout.setVerticalGroup(
            bphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardCounter1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardTitle1)
                .addContainerGap())
        );

        cardIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cardCounter2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cardCounter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardCounter2.setText("counter");

        cardTitle2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cardTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardTitle2.setText("PENGEMBANGAN");

        javax.swing.GroupLayout pengembanganPanelLayout = new javax.swing.GroupLayout(pengembanganPanel);
        pengembanganPanel.setLayout(pengembanganPanelLayout);
        pengembanganPanelLayout.setHorizontalGroup(
            pengembanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengembanganPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pengembanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardCounter2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        pengembanganPanelLayout.setVerticalGroup(
            pengembanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengembanganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardCounter2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardTitle2)
                .addContainerGap())
        );

        cardIcon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cardCounter3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cardCounter3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardCounter3.setText("counter");

        cardTitle3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cardTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardTitle3.setText("PELATIHAN");

        javax.swing.GroupLayout pelatihanPanelLayout = new javax.swing.GroupLayout(pelatihanPanel);
        pelatihanPanel.setLayout(pelatihanPanelLayout);
        pelatihanPanelLayout.setHorizontalGroup(
            pelatihanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelatihanPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pelatihanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(cardCounter3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(cardIcon3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        pelatihanPanelLayout.setVerticalGroup(
            pelatihanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelatihanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardCounter3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardTitle3)
                .addContainerGap())
        );

        cardIcon4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cardCounter4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cardCounter4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardCounter4.setText("counter");

        cardTitle4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cardTitle4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardTitle4.setText("HPD");

        javax.swing.GroupLayout hpdPanelLayout = new javax.swing.GroupLayout(hpdPanel);
        hpdPanel.setLayout(hpdPanelLayout);
        hpdPanelLayout.setHorizontalGroup(
            hpdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hpdPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(hpdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(cardCounter4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(cardIcon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        hpdPanelLayout.setVerticalGroup(
            hpdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hpdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardCounter4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardTitle4)
                .addContainerGap())
        );

        cardIcon5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cardCounter5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cardCounter5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardCounter5.setText("counter");

        cardTitle5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cardTitle5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardTitle5.setText("UMUM");

        javax.swing.GroupLayout umumPanelLayout = new javax.swing.GroupLayout(umumPanel);
        umumPanel.setLayout(umumPanelLayout);
        umumPanelLayout.setHorizontalGroup(
            umumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(umumPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(umumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardTitle5, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(cardCounter5, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(cardIcon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        umumPanelLayout.setVerticalGroup(
            umumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(umumPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardCounter5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardTitle5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pengembanganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pelatihanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hpdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(umumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(umumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pelatihanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pengembanganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bphPanel;
    private javax.swing.JLabel cardCounter1;
    private javax.swing.JLabel cardCounter2;
    private javax.swing.JLabel cardCounter3;
    private javax.swing.JLabel cardCounter4;
    private javax.swing.JLabel cardCounter5;
    private javax.swing.JLabel cardIcon1;
    private javax.swing.JLabel cardIcon2;
    private javax.swing.JLabel cardIcon3;
    private javax.swing.JLabel cardIcon4;
    private javax.swing.JLabel cardIcon5;
    private javax.swing.JLabel cardTitle1;
    private javax.swing.JLabel cardTitle2;
    private javax.swing.JLabel cardTitle3;
    private javax.swing.JLabel cardTitle4;
    private javax.swing.JLabel cardTitle5;
    private javax.swing.JPanel hpdPanel;
    private javax.swing.JPanel pelatihanPanel;
    private javax.swing.JPanel pengembanganPanel;
    private javax.swing.JPanel umumPanel;
    // End of variables declaration//GEN-END:variables
}
